export enum TMarketsListActions {
  RETRIEVE_LIST_START = 'marketsList/RETRIEVE_LIST_START',
  RETRIEVE_LIST_SUCCESS = 'marketsList/RETRIEVE_LIST_SUCCESS',
  RETRIEVE_LIST_ERROR = 'marketsList/RETRIEVE_LIST_ERROR',

  SET_REQUEST_PARAMS = 'marketsList/SET_REQUEST_PARAMS',
}
