export enum TTestActions {
  RETRIEVE_DATA_FETCH_START = 'testModel/RETRIEVE_DATA_FETCH_START',
  RETRIEVE_DATA_FETCH_SUCCESS = 'testModel/RETRIEVE_DATA_FETCH_SUCCESS',
  RETRIEVE_DATA_FETCH_ERROR = 'testModel/RETRIEVE_DATA_FETCH_ERROR',
}
